<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "x4etcpdf"
 *
 * Auto generated by Extension Builder 2015-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tcpdf',
	'description' => '',
	'category' => 'misc',
	'author' => 'Michel Georgy',
	'author_email' => 'michel@4eyes.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);